config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  resources :bosses do
    resources :boss_logs, only: %i[new create edit update]
  end
  resources :boss_logs, only: %i[destroy]

  resources :users

  get 'top/index'

  root to: "top#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/boss_log.rb
class BossLog < ApplicationRecord
  belongs_to :user
  belongs_to :boss
end

app/controllers/boss_logs_controller.rb
class BossLogsController < ApplicationController
  def new
    @user = current_user
    @boss = Boss.find(params[:boss_id])
    @boss_log = @boss.boss_logs.build
  end

  def create
    @user = current_user
    @boss = Boss.find(params[:boss_id])
    @boss_log = @boss.boss_logs.build(boss_log_params)
    @boss_log.update(user_id: @user.id, boss_id:@boss.id)
    if @boss_log.save
      redirect_to edit_boss_boss_log_path(@boss, @boss_log.id)
    else
      redirect_to root_url
    end
  end

  def edit
    @boss_log = BossLog.find(params[:id])
  end

  def update
    @boss_log = BossLog.find(params[:id])
    if params[:commit] == "+"
      @boss_log.update(death_count: @boss_log.death_count+1, comment: boss_log_params[:comment], medicine_count: boss_log_params[:medicine_count], item: boss_log_params[:item], link: boss_log_params[:link])
      render :edit
    elsif params[:commit] == "-"
      @boss_log.update(death_count: @boss_log.death_count-1, comment: boss_log_params[:comment], medicine_count: boss_log_params[:medicine_count], item: boss_log_params[:item], link: boss_log_params[:link])
      render :edit
    elsif params[:commit] == "一時保存"
      @boss_log.update(comment: boss_log_params[:comment], medicine_count: boss_log_params[:medicine_count], item: boss_log_params[:item], link: boss_log_params[:link])
      flash[:note] = '一時保存されました 以下から再開できます'
      redirect_to user_path(@boss_log.user)
    else
      @boss_log.update(comment: boss_log_params[:comment], medicine_count: boss_log_params[:medicine_count], item: boss_log_params[:item], link: boss_log_params[:link], done:true)
      redirect_to boss_path(@boss_log.boss)
    end
  end

  def destroy
    @user = current_user
    @boss_log = BossLog.find(params[:id])
    @boss_log.destroy
    redirect_to user_path(@user)
  end

  private

  def boss_log_params
    params[:boss_log].permit(:death_count, :play_time, :comment, :difficulty, :lap, :medicine_count, :item, :link)
  end
end

app/helpers/boss_logs_helper.rb
module BossLogsHelper
end

app/views/boss_logs/edit.slim
.container
  .row
    .col-12.mb-2
      a href = boss_path(@boss_log.boss)
        span.font-weight-bold.text-info ◀ ボスページに戻る
    .col-12
      = form_for @boss_log, url: boss_boss_log_path do |f|
        /br
          = f.label :lap, "何周目か", class:'control-label'
          = f.number_field :lap, min:"0", step:"1", class:'form-control', :placeholder => "例:1"
        br
        = f.label :death_count, "死亡回数", class:'control-label'
        br
        = f.number_field :death_count, min:"0", step:"1", class:'form-control bg-white col-3 d-inline', :value => @boss_log.death_count, :disabled => true
        = f.submit "+", class:'float-right ml-2 form-control bg-info font-weight-bold text-white border-info col-3 d-inline'
        = f.submit "-", class:'float-right form-control bg-info font-weight-bold text-white border-info col-3 d-inline'
        br
        br
        br
        = f.label :medicine_count, "瓢箪使用回数", class:'control-label'
        br
        = f.number_field :medicine_count, min:"0", step:"1", class:'form-control bg-white col-3 d-inline'
        br
        br
        = f.label :item, "使用アイテム", class:'control-label'
        br
        = f.text_field :item, class:'form-control bg-white col-6'
        br
        = f.label :comment, "勝利後のコメント", class:'control-label'
        = f.text_area :comment, class:'form-control', :value => @boss_log.comment
        br
        = f.label :link, "プレイ動画のリンク", class:'control-label'
        = f.text_field :link, class:'form-control'
        br
        br
        = f.submit "一時保存", class:'float-left col-5 form-control d-inline bg-info font-weight-bold text-white border-info'
        = f.submit "投稿", class:'float-right col-5 form-control d-inline bg-info font-weight-bold text-white border-info'
        - if flash[:note]
          .alert.alert-info.alert-dismissible.fade.show.float-left.mt-2 role="alert" 
            p = flash[:note]
            button.close aria-label="Close" data-dismiss="alert" type="button" 
              span aria-hidden="true"  ×

app/views/boss_logs/new.slim
.container
  .row
    .col-12
      = form_for @boss_log, url: boss_boss_logs_path do |f|
        = f.hidden_field :user_id, value: @user.id
        = f.hidden_field :boss_id, value: @boss.id
        br
        = f.label :lap, "何周目か", class:'control-label'
        = f.number_field :lap, min:"0", step:"1", class:'form-control', :value => 1
        /br
            = f.label :death_count, "死亡回数", class:'control-label'
            = f.number_field :death_count, min:"0", step:"1", class:'form-control', :placeholder => "例:12"
            br
            /= f.label :play_time, "タイム", class:'control-label'
            /= f.time_select :play_time, min:"0", step:"1", class:'form-control', :placeholder => "例:12"
            br
            = f.label :comment, "コメント", class:'control-label'
            = f.text_area :comment, class:'form-control', :placeholder => "無記入でも投稿できます"
        br
        br

        = f.submit "戦闘を開始する", class:'form-control bg-info font-weight-bold text-white border-info'