config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  resources :bosses do
    resources :boss_logs, only: %i[new create edit update]
  end
  resources :boss_logs, only: %i[destroy]

  resources :users

  get 'top/index'

  root to: "top#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  dragonfly_accessor :image
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boss_logs, dependent: :destroy
  has_many :bosses, through: :boss_logs

  def remember_me
    true
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@death_counts = []
  	BossLog.where(user_id:@user.id).where(done:true).each do |boss_log|
      @death_counts << boss_log.death_count
  	end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.slim
.container
  .row
    .col-3
      - if @user.image_stored?
        = image_tag @user.image&.thumb('80x80#').url, class:'img-fluid rounded-circle mx-auto d-block'
      - else
        img.mx-auto.d-block.mt-2.img-fluid.rounded alt="#{@user.name}" width="50" height="50" src=asset_path("mypage-active.png")
    .col-9
      - unless @user.name.nil?
        h1.mb-0.text-theme = @user.name
      - else
        h1.mb-0.text-theme 名無しさん
      - if user_signed_in? and @user.id == current_user.id
        = link_to edit_user_registration_path
          button.btn-block.btn.btn-outline-info.rounded-pill.p-1 type="button"
            span.font-weight-bold.text-theme プロフィールを編集
      br
      span #{@user.profile}
    .col-12.mt-3
      table.table.table-sm.text-white
        tbody
          tr
            th scope="row" 
              span 合計死亡回数
            td
              - unless BossLog.where(user_id:@user.id).nil?
                span.float-right #{@death_counts.compact.sum}回
          tr
            th scope="row" 
              span 現在の周回数
            td
              span.float-right #{@user.lap}周
    - if user_signed_in? and @user.id == current_user.id
      .col-12.mb-5
        h2.text-theme 一時保存中のボス
        - if flash[:note]
          .alert.alert-info.alert-dismissible.fade.show role="alert" 
            p = flash[:note]
            button.close aria-label="Close" data-dismiss="alert" type="button" 
              span aria-hidden="true"  ×
        - @user.boss_logs.where(done:false).sort_by{|boss_log| boss_log.updated_at}.reverse.each do |boss_log|
          .row.border-bottom.mt-3.pb-2
            .col-3
              a href = boss_path(boss_log.boss)
                - if boss_log.boss.image_stored?
                  = image_tag boss_log.boss.image&.thumb('630x355#').url, class:'img-fluid'
                - else
                  img.img-fluid alt="boss" width="" src=asset_path("boss.png")
            .col-9
              - unless boss_log.lap.nil?
                span.font-weight-bold #{boss_log.lap}周目
              - else
                span.font-weight-bold -周目
              span.font-weight-bold.ml-2 #{boss_log.death_count}回死亡
              span.text-theme.text-no-wrap.float-right #{time_ago_in_words(boss_log.updated_at)}
              br
              span.pb-0
                = simple_format(boss_log.comment, :class => "mb-0")
              br
              .row
                .col-6.float-left
                  a href = edit_boss_boss_log_path(boss_log.boss, boss_log.id)
                    button.mt-1.btn.btn-info.btn-block type="button"
                      span.font-weight-bold 再開
                .col-6.float-right
                  = link_to "削除", boss_log_path(boss_log.id), method: :delete, class: 'mt-1 btn btn-info btn-block font-weight-bold', data: { confirm: '本当に削除しますか?' }
                  /= link_to "削除", boss_boss_log_path(boss_log.boss, boss_log.id), method: :delete, class: 'mt-1 btn btn-info btn-block'
                  /a href = boss_log_path(boss_log), method: :delete
                    button.mt-1.btn.btn-info.btn-block type="button"
                      span 削除
    .col-12
      h2.text-theme ボス個人詳細
      - @user.boss_logs.where(done:true).sort_by{|boss_log| boss_log.updated_at}.reverse.each do |boss_log|
        .row.border-bottom.mt-3.pb-2
          .col-3
            a href = boss_path(boss_log.boss)
              - if boss_log.boss.image_stored?
                = image_tag boss_log.boss.image&.thumb('630x355#').url, class:'img-fluid'
              - else
                img.img-fluid alt="boss" width="" src=asset_path("boss.png")
          .col-9
            - unless boss_log.lap.nil?
              span.font-weight-bold #{boss_log.lap}周目
            - else
              span.font-weight-bold -周目
            span.font-weight-bold.ml-2 #{boss_log.death_count}回死亡
            span.text-theme.text-no-wrap.float-right #{time_ago_in_words(boss_log.updated_at)}
            br
            - unless boss_log.medicine_count.nil?
              span.font-weight-bold 瓢箪: #{boss_log.medicine_count}回
            - else
              span.font-weight-bold 瓢箪: -
            - unless boss_log.item.nil?
              span.font-weight-bold.ml-2 アイテム: #{boss_log.item}
            - else
              span.font-weight-bold.ml-2 アイテム: -
            br
            span.pb-0
              = simple_format(boss_log.comment, :class => "mb-0")
            br
            - unless boss_log.link.nil? or boss_log.link == ""
              a href = "http://#{boss_log.link}" target="blank"
                button.mt-1.btn.btn-info.btn-block type="button"
                  span.font-weight-bold プレイ動画
            - if user_signed_in? and current_user.id == @user.id
              a href = edit_boss_boss_log_path(boss_log.boss, boss_log.id)
                button.mt-1.btn.btn-info.btn-block type="button"
                  span.font-weight-bold 編集

    br
    br