config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  resources :bosses do
    resources :boss_logs, only: %i[new create edit update]
  end
  resources :boss_logs, only: %i[destroy]

  resources :users

  get 'top/index'

  root to: "top#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/bosses_controller.rb
class BossesController < ApplicationController
  def index
    @q = Boss.ransack(params[:q])
    @bosses = @q.result(distinct: true)
  end

  def show
  	@boss = Boss.find(params[:id])
    @death_counts = []
    BossLog.where(boss_id:@boss.id).where(done:true).each do |boss_log|
      @death_counts << boss_log.death_count
    end
  end

  private
  def search_params
    params.require(:q).permit(:name_cont)
  end
  
end

app/helpers/bosses_helper.rb
module BossesHelper
end

app/views/bosses/index.slim
.container
  .row
    .col-12
      h1.text-theme ボス一覧
      br
      - unless @bosses.nil?
        - @bosses.all.sort_by{|boss| boss.created_at}.each do |boss|
          .border-bottom.mt-5
            a href = boss_path(boss)
              - if boss.image_stored?
                = image_tag boss.image&.thumb('630x355#').url, class:'img-fluid'
              - else
                img.img-fluid alt="boss" width="" src=asset_path("boss.png")
              br
              h2.text-theme = boss.name
          span.text-theme 初めて倒すまでの平均死亡回数: 
          span.text-white #{BossLog.where(boss_id:boss.id).where(lap: 1).average(:death_count)&.round(1)}
          span.text-theme 回
        - if @bosses.first.nil?
          span.text-white ボスが見つからないときは
          br
          a href = bosses_path
            span.text-theme ボス一覧
          span.text-white から探すか、
          br
          a href = "https://twitter.com/sekironote" target="blank"
            span.text-theme 管理人のツイッター
          span.text-white までDMやリプでご連絡ください。
          br

app/views/bosses/show.slim
.container
  .row
    .col-12.mb-2
      a href = bosses_path
        span.font-weight-bold.text-info ◀ ボス一覧に戻る
    .col-12
      h1.text-theme = @boss.name
    .col-12
      - if @boss.image_stored?
        = image_tag @boss.image&.thumb('630x355#').url, class:'img-fluid'
      - else
        img.img-fluid alt="boss" width="" src=asset_path("boss.png")
      br
      - if user_signed_in?
        = link_to new_boss_boss_log_path(@boss)
          button.mt-1.btn.btn-info.btn-lg.btn-block type="button"
            span.font-weight-bold 挑む
      - else
        .div data-target="#exampleModal" data-toggle="modal"
          button.mt-1.btn.btn-info.btn-lg.btn-block type="button"
            span.font-weight-bold 挑む
    .col-12.mt-5
      span = @boss.info
      table.table.table-sm.text-white.mt-5
        tbody
          tr
            th scope="row" 
              span 初めて倒すまでの平均死亡回数
            td
              - unless BossLog.where(boss_id:@boss.id).nil?
                span.float-right #{BossLog.where(boss_id:@boss.id).where(lap: 1).average(:death_count)&.round(1)}回
          tr
            th scope="row" 
              span 平均死亡回数
            td
              - unless BossLog.where(boss_id:@boss.id).nil?
                span.float-right #{BossLog.where(boss_id:@boss.id).average(:death_count)&.round(1)}回
          tr
            th scope="row"
              span 合計打倒数
            td
              span.float-right #{BossLog.where(boss_id:@boss.id).where(done: true).count}回
          tr
            th scope="row" 
              span 平均勝率
            td
              - unless BossLog.where(boss_id:@boss.id).nil?
                span.float-right #{(BossLog.where(boss_id:@boss.id).where(done: true).count/@death_counts.compact.sum&.to_f)&.round(3)*100}%
    .col-12.mt-5
      h2.text-theme 感想・アドバイス
      - @boss.boss_logs.where(done:true).sort_by{ |boss_log| boss_log.created_at}.reverse.each do |boss_log|
        .row.border-bottom.py-2
          .col-3.mt-1
            a href = user_path(boss_log.user)
              - if boss_log.user.image_stored?
                = image_tag boss_log.user.image&.thumb('46x46#').url, class:'mx-auto d-block img-fluid rounded-circle'
              - else
                img.mx-auto.d-block.mt-2.img-fluid.rounded alt="#{boss_log.user.name}" width="46" height="46" src=asset_path("mypage-active.png")
          .col-9
            - unless boss_log.user.name.nil?
              span.text-theme = boss_log.user.name
            - else
              span.text-theme 名無しさん
            br
            - unless boss_log.lap.nil?
              span.font-weight-bold #{boss_log.lap}周目
            - else
              span.font-weight-bold -周目
            span.font-weight-bold.ml-2 #{boss_log.death_count}回死亡
            span.text-theme.text-no-wrap.float-right #{time_ago_in_words(boss_log.updated_at)}
            br
            - unless boss_log.medicine_count.nil?
              span.font-weight-bold 瓢箪: #{boss_log.medicine_count}回
            - else
              span.font-weight-bold 瓢箪: -
            - unless boss_log.item.nil?
              span.font-weight-bold.ml-2 アイテム: #{boss_log.item}
            - else
              span.font-weight-bold.ml-2 アイテム: -
            br
            /span #{boss_log.play_time}
            = simple_format(boss_log.comment, :class => "mb-0")
            br
            - unless boss_log.link.nil? or boss_log.link == ""
              a href = "http://#{boss_log.link}" target="blank"
                button.mt-1.btn.btn-info.btn-block type="button"
                  span.font-weight-bold プレイ動画
            - if user_signed_in? and current_user.id == boss_log.user.id
              a href = edit_boss_boss_log_path(boss_log.boss, boss_log.id)
                button.mt-1.btn.btn-info.btn-block type="button"
                  span.font-weight-bold 編集